name: Create file
on:
  push
jobs:
  Create-empty-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - run: |
          echo "Creating file"
          today=$(date -I)
          echo "today=$today" >> $GITHUB_ENV
          touch sample_$today.js
          ls -lah

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: user_info
          message: "added on ${{ env.today }}"
