name: Create file
on:
  push
jobs:
  Create-empty-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - run: |
          echo "Creating file"
          echo "today=$(date -I)" >> $GITHUB_ENV
          touch sample_${{ env.today }}.js
          ls -lah

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "added on ${{ env.today }}"
